mode: deployment
image:
  tag: "0.55.0"

clusterRole:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods", "namespaces"]
      verbs: ["get", "watch", "list"]
config:
  receivers:
    otlp/2:
      protocols:
        http:
          endpoint: 0.0.0.0:55566
  exporters:
    logging:
      loglevel: debug
  processors:
    k8sattributes:
      passthrough: false
      extract:
        metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.pod.start_time
      pod_association:
        - from: resource_attribute
          name: k8s.pod.ip
  service:
    telemetry:
      logs:
        level: debug
    pipelines:
      metrics:
        receivers:
          - otlp/2
      traces:
        processors:
          - k8sattributes
          - memory_limiter
          - batch
